### ISSUE TITLE
Landing place for TCF

### ISSUE THREAD

**Issue by marcverhagen** [lapps/schemata#2]
This probably needs to be in `lif.schema` unless we want this to be in the data container.

**Comment by ksuderman** [comment]
I don't understand what you mean by "Landing place for TCF"

**Comment by marcverhagen** [comment]
We need a slot to put the entire TCF representation when we convert from TCF to LIF so that we do not loose information on the way back.

**Comment by keighrim** [comment]
Just adding my two cents. 
If we are doing this, I think it would better off to have general name for slots to contain any external formats. (e.g. `converted-from: TCF`, `original-data`: FULL_TCF_REPRESENTATION`)
I'm not sure we would want to but, then, we can probably re-think the way we deal with UIMA and gate afterwards?

**Comment by marcverhagen** [comment]
Yes, or maybe a slot named `converted` or `source` which has a map as its value so we can stuff in whatever we want.

**Comment by ksuderman** [comment]
Should this go in the container metadata rather than specialized slots? It seems more an implementation detail of the TCF converter rather than something generic enough to be a top level slot. What happens to this data if the document is converted back to TCF?

**Comment by marcverhagen** [comment]
I think putting in the container instead of LIF is probably a good thing. What happens when it is converted back is up to the LIF-TCF converter I would say. What I would do is to take the TCF as it was stored in the container and fill in missing information if you can find it in one of the LIF views. This probably depends on only using same pipelines.

**Comment by marcverhagen** [comment]
Well, we now agree that there are only bad ways and other bad ways of doing this. Solutions either require massive changes to the code or do not easily generalize to other formats like GATE. Also, while conversions may not be lossless, from the users perspective there is no loss because "lost" data are still available in the history.
