### ISSUE TITLE
some problems with `license`, licenseDesc` and versioning

### ISSUE THREAD

**Issue by keighrim** [lapps/schemata#3]
This is a continuation from lappsgrid-services/org.anc.lapps.stanford#12

---

1. _Do we need to show users (either via galaxy or a soap call) how the original software is licensed?_ Yes, and that's why we got together almost a year ago upon the call of @ccieri . 
1. _Do we need to show users how the tool (wrapper) is licensed?_ I don't know. But I'd like to. So far we've used [apache2](https://www.apache.org/licenses/LICENSE-2.0) for wrapper code, and the licenses are all included in the code base (as LICENSE.txt or something like that). The license of the wrapper might be irrelevant to the users (but might be interesting to developers, who are going to access the codebase anyway) and that leads to this question. 
    * _NOTE_ that not all lapps tools are wrappers and there could be a original NLP software written for and within lapps framework. 
1. _Now, how about version?_ We have the `version` field in the tool metadata, but it's being used to publish the version of the wrapper, and there aren't dedicated place to put the version of the actual tool. (One can use tool `description` metadata to indicate the version in prose, but that's probably not machine readable. 
1. Finally, we might have similar problems in other field in the tool metadata.

**Comment by keighrim** [comment]
For license information, 
1. idea
    * use `license` to point to the url (defined in the lapps vocab) of the annotation tool (hereafter "wrappee")
    * use `licnseDesc` to store ''restructured' verbose license description of the "wrappee" to show on galaxy
    * use `LICENSE` file on github repository to store license information of the lapps tool (hereafter "wrapper")
1. idea
    * use `license` to point to the url (defined in the lapps vocab) of the "wrapper"
    * <s>use `licnseDesc` to store ''restructured' verbose license description of the "wrappee" to show on galaxy</s> (the same as 1.)
    * <s>use `LICENSE` file on github repository to store license information of the "wrapper"</s> (the same as 1.)

Any other suggestion?

**Comment by ksuderman** [comment]
I think #1 makes the most sense.

**Comment by keighrim** [comment]
Agreed. Just to confirm, we're leaving `version` as is for now?

**Comment by ksuderman** [comment]
Yes, I think so.  If the underlying tool (the "wrappee") changes we can reflect that in the "wrapper" version.

But maybe we need to rethink our versioning scheme.  We have gone with Semantic Versioning "just because" that is what everyone does, but maybe we need something that reflects the wrapper version as well as the version of the tool being wrapped.  For example, we may have version 1.1.0 of a Galaxy XML tool config for the v2.0.4 Brandeis service that wraps Stanford NLP 2.9.3.

**Comment by keighrim** [comment]
I thought about this, and 100% agree on re-thinking the versioning scheme. With the X.Y.Z semantic versioning scheme, as you might already have noticed, we can't do use the wrappee version in wrapper version directly. At the same time, we should also consider tools that are not wrappers (lapps original tools).

**Comment by keighrim** [comment]
For versioning tools that are wrapped inside Lapps tools, we decided to have an additional field in the tool metadata schema, called `toolVersion`.

**Comment by ksuderman** [comment]
I "think" all of these issues have been addressed and/or resolved.  Can this be closed now?

**Comment by keighrim** [comment]
Yes. I'm closing this.
